version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - redis_app_net
  app-redis:
    build: .
    image: redis-app-images:latest
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - redis_app_net
networks:
  redis_app_net:
    driver: bridge